### ISSUE TITLE
Error while running make in quicdoq. 

### ISSUE THREAD

**Issue by Rusheelraj** [private-octopus/quicdoq#38]
![image](https://github.com/private-octopus/quicdoq/assets/30828807/2a2efa9a-1a0f-47a8-83c8-a1c1272b9df5)

**Comment by huitema** [comment]
Sorry, this is a leftover from the early implementation of ESNI in picotls. This will eventually be raplaced by ECH once the standard stabilizes. Starting PR #39 to fix the issue.
